In [12]:
import torch
import numpy as np

In [13]:
torch.__version__

'1.3.0'

In [14]:
torch.cuda.is_available()

True

In [15]:
torch.version.cuda

'10.1.243'

In [16]:
t = torch.tensor([1,2,3])

In [17]:
t

tensor([1, 2, 3])

In [18]:
t.device

device(type='cpu')

In [19]:
t = t.cuda()

In [20]:
t

tensor([1, 2, 3], device='cuda:0')

In [21]:
t.dtype

torch.int64

In [22]:
t.device

device(type='cuda', index=0)

In [23]:
t.layout

torch.strided

In [24]:
torch.as_tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
t = torch.tensor([[1,2,3],[4,5,6]])

In [26]:
t.reshape(-1)

tensor([1, 2, 3, 4, 5, 6])

In [27]:
t.reshape(6)

tensor([1, 2, 3, 4, 5, 6])